### ISSUE TITLE
guide , contribution & more 

### ISSUE THREAD

**Issue by whoafridi** [niloy143/bn-slug#1]
can you make this more generalized & add more description example in README file so that other can work on this.

**Comment by niloymahmudapu** [comment]
Hi @whoafridi thanks for reaching out.
This package is effortless and straightforward, you import it and call it. There is only one function exported (default) which every time you call, returns a random Bengali slug.

Here is an example:
```javascript
import bnSlug from "bn-slug";
console.log(bnSlug()); // a random slug (string)
console.log(bnSlug()); // another random slug (string)
```
As this is very simple, I didn't add much to the README.md file. I created this package to reuse it in my other projects.

However, the description is changed with details, you may look into it, and let me know if that's okay now.

**Comment by whoafridi** [comment]
okay nice.
